### ISSUE TITLE
Add three Totals rows to Funding table

### ISSUE THREAD

**Issue by jstrangfeld** [dvrpc/pa-tip#72]
- [x] Row 1: column totals for each year
- [x] Row 2: total for first four years
- [x] Row 3: grand total for all twelve years

**Comment by rbeatty1** [comment]
Is the four-year funding total supposed to be shown on the list items? Right now it just says "Total Funding first 4 years".

**Comment by mmolta** [comment]
that was the idea at first, but the funding table is only in the full jawn so getting that info for the results page would require a call to that db which we don't want to do at that point. We should revisit this later because it would be nice to have if we can find a way to include the totals info in the tiles.
